defaults: &settings
  version: 1.0.7
  app_name: Zazo Admin
  app_name_key: admin
  default_per_page: 100

development:
  <<: *settings

test:
  <<: *settings

playground:
  <<: *settings

staging:
  <<: *settings

production:
  <<: *settings
